tasks:
  - name: Python Virtual Environment
    init: |
      cd python/
      python3 -m venv venv --system-site-packages && python3 -m pip install --upgrade pip && source venv/bin/activate && pip install -e .[all]
    command: source venv/bin/activate # Always launch a console with our virtual env

vscode:
  extensions:
    - eamodio.gitlens
    - redhat.vscode-yaml
    - editorconfig.editorconfig
    - streetsidesoftware.code-spell-checker
    - ms-python.python

image:
  file: .gitpod.Dockerfile
