on:
  workflow_call:

jobs:
  build_python_artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install the Python Package
        run: pip install -e .[all]

      - name: List Transitive Dependencies
        run: pipdeptree

      - name: Lint with flake8
        run: flake8 .

      - name: Lint with MyPy
        run: mypy src

      - name: Build distribution package
        run: python setup.py bdist_wheel

      - name: Upload Python Wheel
        uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: dist/
